# -*- coding: utf-8 -*-
# Complete Exhaustive 118 CCTNS Crime Head Mapping

ALL_118_CRIME_HEADS_MAP = {
    1: ["theft", "stolen", "stealing", "larceny", "pilferage", "pickpocket", "mobile theft", "shoplifting", "kallatana", "ಕಳ್ಳತನ"],
    2: ["burglary", "house breaking", "break in", "door break", "window grill", "residential theft", "manebidi", "ಮನೆಗಳ್ಳತನ"],
    3: ["robbery", "armed robbery", "highway robbery", "extortion robbery", "knife point", "mugging", "darode", "ದರೋಡೆ", "ಸುಲಿಗೆ"],
    4: ["dacoity", "armed dacoity", "gang robbery", "hold up", "weapons robbery", "gang dacoity", "dacoits"],
    5: ["murder", "homicide", "killing", "assassination", "slaying", "kole", "ಕೊಲೆ"],
    6: ["attempt to murder", "attempted murder", "murderous attack", "stab attempt", "kole prayatna", "ಕೊಲೆ ಪ್ರಯತ್ನ"],
    7: ["kidnapping", "abduction", "hostage", "kidnap", "apaharana", "ಅಪಹರಣ"],
    8: ["assault", "grievous hurt", "physical attack", "beating", "manhandling", "daali", "ಹಲ್ಲೆ"],
    9: ["cheating", "fraud", "scam", "deception", "impersonation", "420", "vanchane", "ವಂಚನೆ"],
    10: ["fraud", "financial fraud", "chit fund", "investment scam", "ponzi", "hondavani", "ಹಣಕಾಸು ವಂಚನೆ"],
    11: ["cybercrime", "cyber crime", "phishing", "online fraud", "otp fraud", "apk fraud", "telegram scam", "crypto fraud", "mule account", "part time job scam", "sextortion", "cyber", "ಸೈಬರ್ ಅಪರಾಧ"],
    12: ["narcotics", "drug", "ganja", "cocaine", "mdma", "contraband", "ndps", "smuggling", "peddler", "opium", "heroin", "cannabis", "synthetic drugs", "meth", "weed", "charas", "hashish", "ಮಾದಕ ದ್ರವ್ಯ"],
    13: ["arms act", "illegal weapon", "firearm", "country pistol", "desi katta", "ammunition", "gun", "revolver", "shastrastra", "ಶಸ್ತ್ರಾಸ್ತ್ರ"],
    14: ["dowry death", "dowry murder", "varadakshine saavu", "ವರದಕ್ಷಿಣೆ ಸಾವು", "dowry harassment death"],
    15: ["domestic violence", "wife beating", "marital cruelty", "498a", "parihara", "ಗೃಹ ಹಿಂಸಾಚಾರ"],
    16: ["motor vehicle theft", "vehicle theft", "bike theft", "car theft", "scooter theft", "automobile theft", "stolen vehicle", "stolen bike", "vaahana kallatana", "ವಾಹನ ಕಳ್ಳತನ"],
    17: ["chain snatching", "snatch", "necklace", "mangalsutra", "gold chain", "pillion snatch", "bag snatch", "sara kalla", "saragallatana", "ಸರಗಳ್ಳತನ"],
    18: ["sexual offences", "outraging modesty", "sexual harassment", "eve teasing", "laingika dourjanya", "ಲೈಂಗಿಕ ದೌರ್ಜನ್ಯ"],
    19: ["riots", "rioting", "unlawful assembly", "mob violence", "communal riot", "galabhe", "ಗಲಭೆ", "ದಂಗೆ"],
    20: ["arson", "fire attack", "burning property", "benki hachuvudu", "ಬೆಂಕಿ ಹಚ್ಚುವಿಕೆ"],
    21: ["motor vehicle accidents non-fatal", "non-fatal accident", "road accident injury", "bike skid", "vahana apaghatha", "ವಾಹನ ಅಪಘಾತ"],
    22: ["crpc cases", "crpc preventive", "chapter cases", "107 crpc", "110 crpc", "shanti palane"],
    23: ["missing person", "missing", "disappeared", "untraceable", "man missing", "woman missing", "kaanaeyada", "ಕಾಣೆಯಾದ ವ್ಯಕ್ತಿ"],
    24: ["karnataka police act 1963", "kp act", "gambling kp act", "matka", "oc", "betting", "kp act 78", "kp act 87"],
    25: ["karnataka state local act", "ksla", "local excise act", "municipal act violations", "state local law"],
    26: ["motor vehicle accidents fatal", "fatal accident", "road death", "hit and run fatal", "saavu apaghatha", "ಮಾರಕ ವಾಹನ ಅಪಘಾತ"],
    27: ["molestation", "indecent assault", "bad touch", "street harassment", "cheste", "ಚೇಷ್ಟೆ"],
    28: ["public safety", "endangering public", "hazardous act", "public endangerment", "saarvajanika surakshe"],
    29: ["pocso", "minor sexual assault", "child abuse", "protection of children", "pocso act", "makkala laingika"],
    30: ["crpc", "crpc procedural", "preventive bond", "crpc sections", "bond over"],
    31: ["cruelty by husband", "husband harassment", "in-laws cruelty", "dowry mental torture", "patiya dourjanya"],
    32: ["election", "election offence", "booth capturing", "voter bribery", "cash seizure election", "chunavane"],
    33: ["representation of people act 1951 & 1988", "rp act", "electoral malpractice", "corrupt election practice"],
    34: ["cases of hurt", "assault with weapon", "severe injury", "fracture beating", "gayagalu", "ಗಾಯಗಳು"],
    35: ["forgery", "fake document", "forged certificate", "stamp paper forgery", "nakali dakhele", "ನಕಲಿ ದಾಖಲೆ"],
    36: ["scheduled caste and the scheduled tribes", "sc st act", "atrocity", "caste abuse", "poa act", "jaathi nindane"],
    37: ["burglary - night", "night burglary", "burglary night", "night break in", "commercial shutter night", "raatri kallatana"],
    38: ["negligent act", "rash act", "endangering life negligence", "alya negligence", "nirakshate"],
    39: ["attempting to commit offences", "criminal attempt", "incomplete crime", "prayatna", "ಪ್ರಯತ್ನ"],
    40: ["kidnapping and abduction", "ransom kidnapping", "interstate kidnapping", "apaharana baduka"],
    41: ["explosives", "bomb", "dynamite", "gelatin sticks", "detonator", "explosive substances act", "sphotaka"],
    42: ["exposure and abandonment of child", "child abandonment", "abandoned baby", "makkala thyaaga"],
    43: ["consumer", "consumer protection", "black marketing", "consumer cheating", "grahaka vanchane"],
    44: ["offences against public servants (public servant is a victim)", "attack on police", "obstructing government officer", "duty obstruction", "officer assault"],
    45: ["crimes related to women", "women harassment", "offences against women", "mahila dourjanya", "ಮಹಿಳಾ ದೌರ್ಜನ್ಯ"],
    46: ["deaths due to rashness/negligence", "negligent death", "304a death", "medical negligence death", "rash driving death"],
    47: ["communal / religion", "communal clash", "religious tension", "temple defilement", "dharmeeya galabhe"],
    48: ["dowry deaths", "dowry death 304b", "varadakshine saavugalu", "dowry suicide"],
    49: ["criminal breach of trust", "embezzlement", "fund siphoning", "vishvasa droha", "ವಿಶ್ವಾಸದ್ರೋಹ"],
    50: ["prevention of damage to public property act 1984", "pdp act", "bus stone pelting", "public property damage", "sarkari aasthi hani"],
    52: ["animal", "cruelty to animals", "cattle theft", "cow slaughter", "praani dourjanya", "ಪ್ರಾಣಿ ದೌರ್ಜನ್ಯ"],
    53: ["copy right act 1957", "piracy", "copyright infringement", "fake software", "counterfeit media"],
    54: ["post & telegraph,telegraph wires(unlawful possession)act 1950", "telegraph cable theft", "copper wire theft", "telecom cable theft"],
    55: ["antiques (cultural property)", "antique theft", "idol theft", "temple treasure theft", "puratana vasthu"],
    56: ["children act", "juvenile justice", "child labor", "cruelty to juvenile", "jj act"],
    57: ["national security act", "nsa", "preventive detention nsa", "threat to nation"],
    58: ["deaths-miscarriage", "forced abortion", "feticide", "garbha paata saavu", "female feticide"],
    59: ["unlawful activities(prevention)act 1967", "uapa", "terrorist act", "banned organization", "anti-national activity"],
    60: ["defamation", "criminal slander", "character assassination", "maanahanisi", "ಮಾನಹಾನಿ"],
    61: ["criminal conspiracy", "120b", "secret plot", "gang conspiracy", "krura sanghadane"],
    62: ["official security related acts", "official secrets act", "classified leak", "security breach act"],
    63: ["foreigner", "foreigners act", "visa overstay", "illegal immigrant", "passport overstay", "videshi"],
    64: ["attempt to culpable homicide not amounting to murder", "308 ipc attempt", "culpable homicide attempt"],
    65: ["burglary - day", "day burglary", "burglary day", "day housebreak", "hagalina manegallatana"],
    66: ["immoral traffic", "itp act", "brothel raid", "prostitution racket", "sex trafficking", "dhadha"],
    67: ["passport act", "fake passport", "passport fraud", "visa tampering", "passport act violations"],
    68: ["assault or use of criminal force to disrobe woman", "disrobing", "354b assault", "stripping assault"],
    69: ["suicide", "abetment to suicide", "306 bns", "aathmahathye", "ಆತ್ಮಹತ್ಯೆ"],
    70: ["indian electricity act", "power theft", "meter tampering", "illegal power hook", "vidyuth kallatana"],
    71: ["documents & property marks", "fake seal", "forged mark", "property mark tampering", "mudre nakali"],
    72: ["criminal intimidation", "death threat", "extortion threat", "hedarike", "ಬೆದರಿಕೆ"],
    73: ["of abetment", "instigation", "criminal abetment", "sahaya", "ಪ್ರಚೋದನೆ"],
    74: ["giving false information respecting an offence com", "false complaint", "misleading police", "sullu mahiti"],
    75: ["receiving of stolen property", "stolen gold receiver", "pawn broker 411", "fence receiver", "stolen goods buyer"],
    76: ["offences against state", "waging war against india", "sedition against state", "deshadroha"],
    77: ["unnatural sex", "377 unnatural offences", "bestiality", "aswabhavika laingika"],
    78: ["civil rights", "pcr act", "protection of civil rights", "untouchability offence"],
    79: ["wrongful restraint/confinement", "illegal confinement", "hostage holding", "bandhana"],
    80: ["offences related to marriage", "bigamy", "fraudulent marriage", "adultery scam", "vivaha vanchane"],
    81: ["public justice", "perjury", "fabricating evidence", "contempt of authority", "nyaya thappuvike"],
    82: ["buying & selling minor for prostitution", "minor trafficking", "child sex slavery", "minor flesh trade"],
    83: ["adulteration", "food adulteration", "toxic liquor", "hooch", "fake medicine", "kalaberake", "ಕಲಬೆರಕೆ"],
    84: ["failure to appear to court", "court non-appearance", "bail jumper", "proclamation offender", "warrant evasion"],
    85: ["railways act", "train stone pelting", "railway track sabotage", "railway ticket scam", "railway theft"],
    86: ["disobedience to order promulgated by publicservan", "section 144 violation", "curfew breach", "prohibitory order breach"],
    87: ["human trafficking", "human smuggling", "bonded trafficking", "maanavara saagane", "ಮಾನವ ಸಾಗಾಣಿಕೆ"],
    88: ["insulting modesty of women (eve teasing)", "eve teasing", "obscene gestures", "stalking women", "cheste maaduvudu"],
    89: ["criminal misappropriation", "misappropriation of property", "dishonest misappropriation", "durbhalake"],
    90: ["indian motor vehicle", "imv act", "rash driving imv", "drunken driving", "no license driving", "imv rules"],
    91: ["rape", "aggravated rape", "gang rape", "attyachara", "ಅತ್ಯಾಚಾರ"],
    92: ["poisoning-professional", "professional poisoner", "cyanide poisoning", "poison robbery", "visha pravega"],
    93: ["prevention of corruption act 1988", "pc act", "bribe", "lokayukta trap", "corruption case", "lancha", "ಲಂಚ"],
    94: ["cotpa, cigarettes and other tobacco products", "cotpa act", "hookah bar raid", "illegal tobacco near school", "cotpa"],
    95: ["defence forces offences relating to (also relating to desertion)", "military desertion", "army uniform impersonation", "defence offence"],
    96: ["false evidence", "giving false evidence", "perjury under oath", "fabricated witness", "sullu saakshya"],
    97: ["arms act 1959", "arms act violation", "country pistol seizure", "unlicensed revolver", "ammunition possession"],
    98: ["escape from lawful custody and resistance", "police lockup escape", "jail break", "custody escape", "kaidi odi"],
    99: ["bonded labour system", "bonded labour abolition act", "forced servitude", "jeetha paddhathi", "ಜೀತ ಪದ್ಧತಿ"],
    100: ["pornography", "obscene publication", "child pornography csam", "porn video racket", "ashleela"],
    101: ["impersonation", "cheating by impersonation", "fake ips officer", "fake government official", "roopa dharisi"],
    102: ["slavery", "slave trade", "buying persons as slaves", "gulamagiri"],
    103: ["unnatural death (sec 174/174c/176)", "174 crpc", "unnatural death", "udr case", "suspicious death", "aswabhavika saavu"],
    104: ["public nuisance", "noise pollution", "public obstruction", "saarvajanika thondare"],
    105: ["offences promoting enemity", "153a hate speech", "communal enmity", "provocative speech", "dvesha"],
    106: ["culpable homicide not amounting to murder", "304 culpable homicide", "accidental death fight", "homicide without premeditation"],
    107: ["criminal trespass", "house trespass", "land grabbing trespass", "anadhikrutha pravesha", "ಅನಧಿಕೃತ ಪ್ರವೇಶ"],
    108: ["affray", "public fight", "street fight", "disturbing peace brawl", "kallatana jagala"],
    109: ["forest", "forest act", "sandalwood smuggling", "poaching tiger", "timber theft", "aranya aparaadha", "ಅರಣ್ಯ ಅಪರಾಧ"],
    110: ["sedition", "anti-national speech", "sedition 124a", "deshadroha bhashana"],
    111: ["infanticide", "killing of newborn", "infant murder", "shishu hatye", "ಶಿಶು ಹತ್ಯೆ"],
    112: ["narcotic drugs & pshycotropic substances", "commercial ndps", "ndps trafficking", "synthetic drug racket", "ndps act"],
    113: ["concealment of birth by secret disposal of child", "secret disposal of infant", "foetus disposal", "janana guptha"],
    114: ["cinematograph act 1952", "movie piracy", "unauthorized theatrical recording", "film certification breach"],
    115: ["cyber crime", "cyber fraud", "information technology act 2000", "it act 66c", "it act 66d", "ransomware", "data theft"],
    116: ["mischief", "property damage", "sabotage", "arson mischief", "nasa maaduva aparaadha"],
    117: ["offences by public servants (except corruption) (public servant is accused)", "police excess", "custodial torture", "public servant offence"],
    118: ["illegal detention", "wrongful detention", "unlawful custody", "illegal arrest", "anadhikrutha bandhana"],
    119: ["counterfeiting", "fake currency", "counterfeit notes", "ficn", "fake currency printing", "nakali note", "ನಕಲಿ ನೋಟು"]
}

print(f"Total Crime Heads Mapped: {len(ALL_118_CRIME_HEADS_MAP)}")
